In [0]:
from fractions import Fraction

In [0]:
import numpy as np
import random
from collections import defaultdict

In [0]:
map_size = 16
def create_empty_map_v1(map_size):
    if isinstance(map_size, int):
        if map_size >=6:
            # create empty map with aaditional place for external walls
            map_obj = np.zeros((map_size+2, map_size+2), dtype=int)
            # add external walls
            map_obj[0], map_obj[-1] = 1, 1
            for i in range(map_size+2):
                map_obj[i][0], map_obj[i][-1] = 1, 1

            # add room, with side of half of the map size
            room_size = map_size//2
            map_obj[-(room_size+1)][-(room_size+1):] = 1
            for j in range(room_size):
                map_obj[-(j+1)][-(room_size+1)]=1

            # add doors in both walls of the room
            map_obj[-(room_size+1)][-2:-1] = 0
            map_obj[-(room_size-1)][-(room_size+1)] = 0
            return(map_obj)
        elif map_size < 6 and map_size >= 0:
            print('Error: map size is too small, correct size is 6+')
    else:
        print('Error: incorrect map size type: expected int')

In [4]:
map_1 = create_empty_map_v1(16)
map_1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,

In [0]:
a = Fraction('1/3')

In [6]:
float(a)

0.3333333333333333

In [0]:
class segment:
    def __init__(self, begin, end):
        self.begin = min(begin, end)
        self.end = max(end, begin)
    def __sub__(self, seg_b):
        if(seg_b.begin >= self.end or seg_b.end <= self.begin):
            return segment(self.begin, self.end)
        elif (self.begin >= seg_b.begin and self.end <= seg_b.end):
            return segment(0, 0)
        else:
            if seg_b.end <= self.end:
                return segment(seg_b.end, self.end)
            else:
                return segment(self.begin, seg_b.begin)
            return segment
    def __add__(self, seg_b):
        if(seg_b.begin >= self.end or seg_b.end <= self.begin):
            return segment(self.begin, self.end)
        else:
            return segment(min(self.begin, seg_b.begin), max(self.end, seg_b.end))
    def len(self):
        return self.end - self.begin

def intersect(seg_a, seg_b):
    if(seg_b.begin >= seg_a.end or seg_b.end <= seg_a.begin):
        return False
    return True

In [8]:
a = segment(0, 1)
b = segment(0, 0.5)
(a - b).len()

0.5

In [9]:
float(Fraction(1, 2))

0.5

In [0]:
class segment:
    def __init__(self, begin, end):
        self.begin = min(begin, end)
        self.end = max(end, begin)
    def __sub__(self, seg_b):
        if(seg_b.begin >= self.end or seg_b.end <= self.begin):
            return segment(self.begin, self.end)
        elif (self.begin >= seg_b.begin and self.end <= seg_b.end):
            return segment(0, 0)
        else:
            if seg_b.end <= self.end:
                return segment(seg_b.end, self.end)
            else:
                return segment(self.begin, seg_b.begin)
            return segment
    def __add__(self, seg_b):
        if(seg_b.begin >= self.end or seg_b.end <= self.begin):
            return segment(self.begin, self.end)
        else:
            return segment(min(self.begin, seg_b.begin), max(self.end, seg_b.end))
    def len(self):
        return self.end - self.begin

def intersect(seg_a, seg_b):
    if(seg_b.begin >= seg_a.end or seg_b.end <= seg_a.begin):
        return False
    return True

def visible_diag(map, player, direction, length = 100):
    closed = []
    res = np.zeros(map.shape, dtype=int)
    res[player] = 1
    for sight in range(1, length + 1):
        for x in range(sight + 1):
            check = (player[0] + x * direction[0], player[1] + (sight - x) * direction[1])
            if check[0] >= len(map) or check[1] >= len(map[0]) or check[0] < 0 or check[1] < 0:
                pass
            else:
                if len(closed) == 0:
                    res[check] = 1
                else:
                    cur_seg = segment(Fraction(x, (sight + 1)), Fraction((x + 1), (sight + 1)))
                    #print(float(cur_seg.len()))
                    for i in closed:
                        #if(check == (10, 10)):
                            #print(cur_seg.begin, cur_seg.end)
                        if intersect(cur_seg, i):
                            cur_seg = cur_seg - i
                        #if(check == (10, 10)):
                            #print()
                            #print(cur_seg.begin, cur_seg.end)
                    if cur_seg.len() > 0:
                        res[check] = 1
                    else:
                        res[check] = 0
                if(map[check] == 1):
                    #print(check)
                    closed.append(segment(Fraction(x, (sight + 1)), Fraction((x + 1), (sight + 1))))
    return res

def visible(map, player, dir, length = 100):
    dirs = [(-1, 0), (-1, 1), (0, 1), (1, 1), (1, 0), (1, -1), (0, -1), (-1, -1)]

    direction = dirs[dir]
    if direction[0] != 0 and direction[1] != 0:
        return visible_diag(map, player, direction, length = 100)
    elif direction[0] != 0:
        res1 = visible_diag(map, player, (direction[0], 1), length = 100)
        res2 = visible_diag(map, player, (direction[0], -1), length = 100)
        res3 = np.zeros(map.shape, dtype=int)
        
        res3[player] = 1
        for x in range(1, length + 1):
            for y in range(x + 1):
                check = (player[0] + x * direction[0], player[1] + y)
                if check[0] >= len(map) or check[1] >= len(map[0]) or check[0] < 0 or check[1] < 0 or x + y > length:
                    pass
                else:
                    res3[check] = 1
                check = (player[0] + x * direction[0], player[1] - y)
                if check[0] >= len(map) or check[1] >= len(map[0]) or check[0] < 0 or check[1] < 0 or x + y > length:
                    pass
                else:
                    res3[check] = 1
        return np.maximum(res1, res2) * res3
    else:
        res1 = visible_diag(map, player, (1, direction[1]), length = 100)
        res2 = visible_diag(map, player, (-1, direction[1]), length = 100)
        res3 = np.zeros(map.shape, dtype=int)
        
        res3[player] = 1
        for x in range(1, length + 1):
            for y in range(x + 1):
                check = (player[0] + y, player[1] + x * direction[1])
                if check[0] >= len(map) or check[1] >= len(map[0]) or check[0] < 0 or check[1] < 0 or x + y > length:
                    pass
                else:
                    res3[check] = 1
                check = (player[0] - y, player[1] + x * direction[1])
                if check[0] >= len(map) or check[1] >= len(map[0]) or check[0] < 0 or check[1] < 0 or x + y > length:
                    pass
                else:
                    res3[check] = 1
        return np.maximum(res1, res2) * res3

In [11]:
np.array([1, 2]) * np.array([2, 3])

array([2, 6])

In [22]:
print(visible(map_1, (8, 8), 7))
print(map_1)

[[0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 

In [0]:
len(map_1[0])

18

In [0]:
(0, 1) > (1, 2)

False